# -*- coding: utf-8 -*-
"""Decision-Maker Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13h3TY8t_2cPOAWSv1zJ2NGxFYIET2OZc
"""

# ==========================================
# Decision Maker for Claim Veracity Evaluation
# ==========================================

from typing import List, Optional

class Evidence:
    """
    Represents a single piece of evidence with its weighted characteristics.
    """
    def __init__(self,
                 credibility: float,   # Ci
                 stance: int,          # Si ∈ {-1, 0, +1}
                 confidence: float,    # Confi
                 quality: Optional[float] = 1.0,  # Qi (optional)
                 recency_weight: Optional[float] = 1.0):  # wT (optional)
        self.credibility = credibility
        self.stance = stance
        self.confidence = confidence
        self.quality = quality
        self.recency_weight = recency_weight

    def weighted_score(self) -> float:
        """
        Compute the per-evidence weighted score:
            Ei = Ci × Si × Confi × Qi × wT
        """
        return (self.credibility *
                self.stance *
                self.confidence *
                self.quality *
                self.recency_weight)

class DecisionMaker:
    """
    Aggregates evidence to compute a Claim Truth Score (CTS)
    and determines the final decision (True, Fake, Unknown).
    """
    def __init__(self, evidence_items: List[Evidence]):
        self.evidence_items = evidence_items

    def compute_cts(self) -> float:
        """
        Compute the normalized Claim Truth Score (CTS):
            CTS = Σ(Ei) / Σ(Ci)
        """
        total_weighted = sum(e.weighted_score() for e in self.evidence_items)
        total_credibility = sum(e.credibility for e in self.evidence_items)
        if total_credibility == 0:
            return 0.0
        return total_weighted / total_credibility

    def decision(self) -> str:
        """
        Translate CTS into discrete decisions:
            - True: CTS ≥ +0.3 and ≥ 2 credible supports
            - Fake: CTS ≤ −0.3 and ≥ 2 credible refutations
            - Unknown: otherwise
        """
        cts = self.compute_cts()

        # Threshold for credible evidence (tunable)
        credible_threshold = 0.6

        # Count credible supports/refutations
        supports = sum(1 for e in self.evidence_items
                       if e.stance == +1 and e.credibility >= credible_threshold)
        refutes = sum(1 for e in self.evidence_items
                      if e.stance == -1 and e.credibility >= credible_threshold)

        if cts >= 0.3 and supports >= 2:
            verdict = "True"
        elif cts <= -0.3 and refutes >= 2:
            verdict = "Fake"
        else:
            verdict = "Unknown"

        return verdict, cts

# ==========================================
# Example Usage
# ==========================================

if __name__ == "__main__":
    # Example concrete inputs
    evidence_list = [
        Evidence(credibility=0.9, stance=+1, confidence=0.8, quality=0.9, recency_weight=1.0),
        Evidence(credibility=0.7, stance=+1, confidence=0.6, quality=0.8, recency_weight=0.9),
        Evidence(credibility=0.8, stance=-1, confidence=0.7, quality=1.0, recency_weight=0.8)
    ]

    decision_maker = DecisionMaker(evidence_list)
    verdict, cts = decision_maker.decision()

    print(f"Claim Truth Score (CTS): {cts:.3f}")
    print(f"Final Decision: {verdict}")

verdict, cts = decision_maker.decision()

# Store decision output in a temporary JSON variable
decision_json = {
    "verdict": verdict,
    "claim_truth_score": round(cts, 4),
    "decision_thresholds": {
        "true_threshold": 0.3,
        "fake_threshold": -0.3,
        "credible_source_threshold": 0.6,
        "minimum_sources": 2
    },
    "model_info": {
        "model_name": "Evidence-Weighted Decision Maker",
        "formula": "CTS = Σ(Ci × Si × Confi × Qi × wT) / Σ(Ci)",
        "version": "1.0"
    }
}

# Try appending if claim_json exists
if "claim_json" in globals():
    claim_json["decision"] = decision_json
    print("Decision appended to claim_json.")
else:
    print("claim_json not found — decision stored in variable `decision_json` only.")

import json

print(json.dumps(decision_json, indent=2))